keycloak:
  url: "http://localhost:8080"
  realm: "metacode"
  client_id: "auth_service_client"
  client_secret: "6szJ4bWcnbffk6DR09LIGpFHC2kl51Gf"

server:
  port: 8081
  frontend_url: "http://localhost:5173" # base URL for links

email:
  smtp_host: "localhost"
  smtp_port: 1025
  smtp_user: "noreply@example.com"
  smtp_pass: "password"
  from: "noreply@example.com"

jwt:
  secret: "supersecretkey"
  expiration_minutes: 5